server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment
  cloud:
    consul:
      host: 192.168.168.129
      port: 8500
      discovery:
        hostname: 192.168.1.115
        service-name: ${spring.application.name}
